name: Build executable
on:
  push:
    tags:
      - "v*" # v1.0
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-executable.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Only run this job if the workflow was triggered by a tag push
    steps:
      - run: |
          pip install poetry
          poetry install
          poetry run build-executable
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.exe
          path: ${{ github.workspace }}/dist/main.exe
          retention-days: 10
